spring:
  thymeleaf:
    cache: true
    check-template-location: true
    enabled: true
    encoding: utf-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    excluded-view-names:
    template-resolver-order: